# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Mod Properties
mod_version=1.5.0
maven_group=dev.xpple
archives_base_name=netherbedrockcracker

# Minecraft properties
minecraft_version=26.3
minecraft_dependency_version=26.3.x

# Fabric Properties
# check these on https://fabricmc.net/develop
fabric_api_version=0.160.7+26.3
fabric_loader_version=0.19.5
fabric_loom_version=1.17-SNAPSHOT

# Library dependencies
clientarguments_version=1.14.0
mc_core_version=eee662999e9f3fe037476b6940dbd6d5e23cdbb6

devauth_version=1.2.2

# Test dependencies
junit_version=5.13.3
