name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  compile-nbc:
    name: Compile Nether Bedrock Cracker to shared library
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Compile shared library (ubuntu-latest)
        if: matrix.os == 'ubuntu-latest'
        working-directory: src/main/rust
        run: |
          cargo build --release
          mv target/release/liblibbedrockcracker.so ../resources/libbedrockcracker.so
      - name: Compile shared library (macos-latest)
        if: matrix.os == 'macos-latest'
        working-directory: src/main/rust
        run: |
          rustup target add aarch64-apple-darwin x86_64-apple-darwin
          cargo build --release --target aarch64-apple-darwin
          cargo build --release --target x86_64-apple-darwin
          lipo -create -output ../resources/libbedrockcracker.dylib target/aarch64-apple-darwin/release/liblibbedrockcracker.dylib target/x86_64-apple-darwin/release/liblibbedrockcracker.dylib
      - name: Compile shared library (windows-latest)
        if: matrix.os == 'windows-latest'
        working-directory: src/main/rust
        run: |
          cargo build --release
          mv target/release/libbedrockcracker.dll ../resources
      - name: Compute SHA256 hash (ubuntu-latest)
        if: matrix.os == 'ubuntu-latest'
        run: sha256sum src/main/resources/libbedrockcracker.so
      - name: Compute SHA256 hash (macos-latest)
        if: matrix.os == 'macos-latest'
        run: shasum -a 256 src/main/resources/libbedrockcracker.dylib
      - name: Compute SHA256 hash (windows-latest)
        if: matrix.os == 'windows-latest'
        run: Get-FileHash -Algorithm SHA256 src/main/resources/libbedrockcracker.dll

      - name: Capture shared library (ubuntu-latest)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: libbedrockcracker.so
          path: src/main/resources/libbedrockcracker.so
      - name: Capture shared library (macos-latest)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: libbedrockcracker.dylib
          path: src/main/resources/libbedrockcracker.dylib
      - name: Capture shared library (windows-latest)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: libbedrockcracker.dll
          path: src/main/resources/libbedrockcracker.dll

  build:
    name: Build Nether Bedrock Cracker Mod
    needs: compile-nbc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Capture shared library
        uses: actions/download-artifact@v4
        with:
          pattern: libbedrockcracker.*
          merge-multiple: true
          path: src/main/resources/
      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Setup JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: 'temurin'
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
      - name: Capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NetherBedrockCracker
          path: build/libs/
